# Generated by Django 5.0.4 on 2024-04-26 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stackbase', '0004_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-date_created']},
        ),
    ]
