# Generated by Django 5.0.4 on 2024-05-25 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stackbase', '0007_poll'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Poll',
        ),
    ]
