# Generated by Django 5.0.4 on 2024-05-26 18:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stackbase', '0009_poll'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
